name: "+ Post a Listing Form"
description: Mobile-friendly shop entry template
title: "[Listing]: New Gear Offer"
labels: ["market-listing"]
body:
  - type: input
    id: itemName
    attributes:
      label: Gear Item
      placeholder: "e.g. Laser Rifle"
    validations:
      required: true
  - type: input
    id: baseStat
    attributes:
      label: Base Stat
      placeholder: "e.g. Weapon, HP, Engine"
    validations:
      required: true
  - type: input
    id: sidestat
    attributes:
      label: Sidestat
      placeholder: "e.g. +0.6 Attack"
    validations:
      required: true
  - type: input
    id: price
    attributes:
      label: Price
    validations:
      required: false
  - type: input
    id: ign
    attributes:
      label: In-Game Username
      placeholder: "Your PSS captain name"
    validations:
      required: true
